models:
   - name: stg_tpch_lineitem
     description: "Lineitem table in staging layer"   
     columns:
       - name: quantity
         description: "Line item Quantity"
         tests:
           - is_positive 

       - name: l_extendedprice
         description: "Line item extended price"
         tests:
           - is_positive      

       - name: l_discount
         description: "Line item discount"
         tests:
            - is_positive 

       - name: l_tax
         description: "Line item tax"
         tests:
            - is_positive       



   - name: stg_tpch_part       
     description: "Part table in staging layer"
     columns:
       - name: retail_price
         description: "Retail price by part type"       
         tests:
           - is_positive

       - name: size
         description: "Part/order size "
         tests: 
           - is_positive

       - name: part_key
         description: "Primary key"
         tests: 
           - unique
           - not_null

   - name: stg_tpch_partsupp
     description: "Part Supplier table in staging layer"
     columns:
       - name: available_quantity
         description: "Available inventory"
         tests:
           - is_positive 

       - name: supply_cost
         description: "Supply Cost table in staging layer"
         tests:
            - is_positive
       - name: supplier_key
         description: "Primary Key"       
         tests:
            - not_null
            - unique

   - name: stg_tpch_orders
     description: "Orders table in staging layer"
     columns:
      - name: total_price
        description: "Total Price per order"
        tests:
              - is_positive 
      - name: order_key
        description: "Primary Key"
        tests:
            - unique
            - not_null


   - name: stg_tpch_customer
     description: "Customer table in staging layer"
     columns:
       - name: customer_key
         description: "Primary Key"
         tests:
            - unique
            - not_null